services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - event-booking

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - event-booking
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  event-booking:
    driver: bridge

volumes:
  postgres_data: {}